### ISSUE TITLE
🐛 Status description length in title block

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/document-issue#35]
**Describe the bug**
Support longer text for `status description`

![image](https://github.com/maxfordham/aectemplater/assets/21370980/4029064f-7255-4c21-a3f9-df06837a60bb)

**Comment by ollyhensby** [comment]
Add max length to pydantic model for `status description`

**Comment by jgunstone** [comment]
also looks like we could shift things over a little: 
![image](https://github.com/maxfordham/document-issue/assets/21370980/564ee730-1bb7-4499-bd3e-078f0ecc955a)

**Comment by ollyhensby** [comment]
Status description was swapped with issue date and shown in the above image in this commit: https://github.com/maxfordham/document-issue/commit/167f6baef306e2554d78db40d4ae115d3b454a9c
