### ISSUE TITLE
✨ create A4 document footer output format

### ISSUE THREAD

**Issue by jgunstone** [maxfordham/document-issue#93]
i.e. like this:

<img width="374" alt="image" src="https://github.com/user-attachments/assets/c5f39888-e37d-4302-8203-901d34d21a0f" />

**Comment by ollyhensby** [comment]
- [ ] Try split up current extension into partial files.
- [ ] Create extension for PDF report.
- [ ] Rename current extension to pdf-schedule.
- [ ] Ensure new extension has consistent formatting.

**Comment by jgunstone** [comment]
r.e. names, lets discuss: 
maybe: 

- `document-issue-report` -> has the front page, contributors, toc
- `document-issue-note` -> the above format
